/*
 * ST7701S init sequence — Makerfabs MaTouch 2.1" 480x480 ROUND panel.
 *
 * WHY THIS FILE EXISTS
 *
 * esp_lcd_st7701 ships a default init table, and on this panel it produces a
 * completely black screen with no error at all: the driver reports success,
 * the backlight lights, and direct esp_lcd_panel_draw_bitmap() writes show
 * nothing. That was verified on hardware before this table was written.
 *
 * The reason is the GIP / gate-driver block, registers 0xE0-0xEF in Command2
 * BK1. Those program the panel's gate and source scan waveforms, and they
 * are supplied by the MODULE maker, not the silicon vendor -- so they differ
 * between panels using the same ST7701S controller. Espressif's defaults are
 * for a different panel; e.g. its 0xEB is {00 01 E4 E4 44 88 00} against this
 * panel's {00 00 40 40 00 00 00}, and it omits 0xCD entirely. With the wrong
 * values the RGB bus clocks pixels in perfectly while the glass never scans.
 * Uniform black, no diagnostic.
 *
 * PROVENANCE
 *
 * Transcribed from `st7701_type5_init_operations` in Arduino_GFX,
 * src/display/Arduino_RGB_Display.h (present identically from tag v1.3.2
 * through v1.6.8). That is the table Makerfabs' own firmware passes --
 * example/fw_test/fw_test.ino constructs Arduino_ST7701_RGBPanel with
 * st7701_type5_init_operations -- and Arduino_GFX's own board header
 * describes type5 as the 2.1" round display.
 *
 * NOT hand-typed: generated by parsing the Arduino_GFX opcode stream
 * (WRITE_C8_D8 / WRITE_C8_D16 / WRITE_COMMAND_8 + WRITE_BYTES / DELAY,
 * semantics per src/Arduino_DataBus.cpp) and emitting this array. 38
 * commands, 173 parameter bytes.
 *
 * CORROBORATION
 *
 * Waveshare's ESP32-S3-Touch-LCD-2.1 -- a different vendor's 2.1" round
 * 480x480 ST7701S -- ships an ESP-IDF table that is byte-identical to this
 * one across the entire GIP block (0xCD, 0xE0-0xEF, 0xEB, 0xED) and the BK1
 * power registers. The two differ only in gamma (0xB0/0xB1), VOP, VCOM and
 * COLMOD. That shared core is the round-panel signature, and two independent
 * vendors agreeing on it is good evidence the values are right.
 *
 * If the panel comes up but looks wrong -- washed out, wrong contrast --
 * Waveshare's gamma/VOP/VCOM are the sane thing to try next, not these.
 */
#pragma once

#include "esp_lcd_st7701.h"

/*
 * Note on 0x3A (COLMOD) near the end: it selects 18-bit, not 16-bit, even
 * though the bus is 16-bit RGB565 -- the 16 lines map to the upper bits of an
 * 18-bit interface. Both vendors do this. esp_lcd_st7701 sends its own COLMOD
 * derived from bits_per_pixel BEFORE this table runs, so this entry overrides
 * it, which is the intended behaviour. The driver logs a warning that 0x3A
 * "will be overwritten by external initialization sequence" -- that is
 * expected and correct here.
 *
 * Likewise the driver sends 0xFF {77,01,00,00,00} (Command2 disabled) before
 * this table, which is why the first entry must re-open BK0.
 */
static const st7701_lcd_init_cmd_t matouch21_round_init[] = {
    {0xFF, (uint8_t []){0x77, 0x01, 0x00, 0x00, 0x10}, 5, 0},
    {0xC0, (uint8_t []){0x3B, 0x00}, 2, 0},
    {0xC1, (uint8_t []){0x0B, 0x02}, 2, 0},
    {0xC2, (uint8_t []){0x00, 0x02}, 2, 0},
    {0xCC, (uint8_t []){0x10}, 1, 0},
    {0xCD, (uint8_t []){0x08}, 1, 0},
    {0xB0, (uint8_t []){0x02, 0x13, 0x1B, 0x0D, 0x10, 0x05, 0x08, 0x07, 0x07, 0x24, 0x04, 0x11, 0x0E, 0x2C, 0x33, 0x1D}, 16, 0},
    {0xB1, (uint8_t []){0x05, 0x13, 0x1B, 0x0D, 0x11, 0x05, 0x08, 0x07, 0x07, 0x24, 0x04, 0x11, 0x0E, 0x2C, 0x33, 0x1D}, 16, 0},
    {0xFF, (uint8_t []){0x77, 0x01, 0x00, 0x00, 0x11}, 5, 0},
    {0xB0, (uint8_t []){0x5D}, 1, 0},
    {0xB1, (uint8_t []){0x43}, 1, 0},
    {0xB2, (uint8_t []){0x81}, 1, 0},
    {0xB3, (uint8_t []){0x80}, 1, 0},
    {0xB5, (uint8_t []){0x43}, 1, 0},
    {0xB7, (uint8_t []){0x85}, 1, 0},
    {0xB8, (uint8_t []){0x20}, 1, 0},
    {0xC1, (uint8_t []){0x78}, 1, 0},
    {0xC2, (uint8_t []){0x78}, 1, 0},
    {0xD0, (uint8_t []){0x88}, 1, 0},
    {0xE0, (uint8_t []){0x00, 0x00, 0x02}, 3, 0},
    {0xE1, (uint8_t []){0x03, 0xA0, 0x00, 0x00, 0x04, 0xA0, 0x00, 0x00, 0x00, 0x20, 0x20}, 11, 0},
    {0xE2, (uint8_t []){0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, 13, 0},
    {0xE3, (uint8_t []){0x00, 0x00, 0x11, 0x00}, 4, 0},
    {0xE4, (uint8_t []){0x22, 0x00}, 2, 0},
    {0xE5, (uint8_t []){0x05, 0xEC, 0xA0, 0xA0, 0x07, 0xEE, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, 16, 0},
    {0xE6, (uint8_t []){0x00, 0x00, 0x11, 0x00}, 4, 0},
    {0xE7, (uint8_t []){0x22, 0x00}, 2, 0},
    {0xE8, (uint8_t []){0x06, 0xED, 0xA0, 0xA0, 0x08, 0xEF, 0xA0, 0xA0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, 16, 0},
    {0xEB, (uint8_t []){0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x00}, 7, 0},
    {0xED, (uint8_t []){0xFF, 0xFF, 0xFF, 0xBA, 0x0A, 0xBF, 0x45, 0xFF, 0xFF, 0x54, 0xFB, 0xA0, 0xAB, 0xFF, 0xFF, 0xFF}, 16, 0},
    {0xEF, (uint8_t []){0x10, 0x0D, 0x04, 0x08, 0x3F, 0x1F}, 6, 0},
    {0xFF, (uint8_t []){0x77, 0x01, 0x00, 0x00, 0x13}, 5, 0},
    {0xEF, (uint8_t []){0x08}, 1, 0},
    {0xFF, (uint8_t []){0x77, 0x01, 0x00, 0x00, 0x00}, 5, 0},
    {0x36, (uint8_t []){0x08}, 1, 0},
    {0x3A, (uint8_t []){0x60}, 1, 0},
    {0x11, (uint8_t []){0x00}, 0, 100},
    {0x29, (uint8_t []){0x00}, 0, 50},

    /*
     * Tail. Arduino_GFX does not stop at the table -- Arduino_ST7701_RGBPanel
     * ::begin() sends these afterwards, and the panel is only correct with
     * them. Easy to miss by reading the table alone.
     *
     *   setRotation(0) with _bgr = true  -> 0xC7 = 0x00, then MADCTL = 0x00
     *   invertDisplay(false) with ips = false -> 0x20 (INVOFF)
     *
     * Note MADCTL ends up 0x00, overriding the 0x08 set in the table above.
     */
    {0xFF, (uint8_t []){0x77, 0x01, 0x00, 0x00, 0x10}, 5, 0},
    {0xC7, (uint8_t []){0x00}, 1, 0},
    {0xFF, (uint8_t []){0x77, 0x01, 0x00, 0x00, 0x00}, 5, 0},
    {0x36, (uint8_t []){0x00}, 1, 0},
    {0x20, (uint8_t []){0x00}, 0, 0},
};

#define MATOUCH21_ROUND_INIT_COUNT \
    (sizeof(matouch21_round_init) / sizeof(matouch21_round_init[0]))
